### ISSUE TITLE
[iOS 9.2.1] Plugin can only be used once

### ISSUE THREAD

**Issue by nickzorb** [mauron85/cordova-plugin-background-geolocation#46] opened 2016-03-01 09:28 UTC
I am testing the plugin on an iphone 6 running iOS 9.2.1.
I will configure the plugin and then call start and changePace. The plugin works as expected providing periodic location updates. Then I call stop, which works as expected stopping the location updates. 

After that however I am unable to get periodic updates again, I've tried calling start and changePace again with no effect, I've also tried calling configure again and then calling start and change pace. In all scenarios I've tried I can't get the plugin to run the success (or error) callback again.

**Comment by mauron85** [comment] 2016-03-01 11:47
Thank you for the report. Need to take look at it.

**Comment by TraceDeTrail** [comment] 2016-03-22 11:50
Hello,

I have the same issue with iOS 9.2 / 9.3... Could you take a look ?

Thanks !

**Comment by TraceDeTrail** [comment] 2016-03-22 14:48
I modified the start function like this : 
    // if (state == UIApplicationStateBackground) {
        [self setPace:isMoving];
   // }
(two lines in comment)
It seems to be ok...

**Comment by mauron85** [comment] 2016-04-16 08:44
Ok. This seems like a bug. Need to take a look on this one.

**Comment by TraceDeTrail** [comment] 2016-04-16 09:17
Ok. Thank you for your response and for this plugin !

**Comment by mauron85** [comment] 2016-05-08 12:52
possible duplicate of #39

**Comment by mauron85** [comment] 2016-06-03 10:50
Please try version 1.0.1. Reopen if necessary.

**Closed by mauron85** 2016-06-03 10:50 UTC
Labels: bug
