### ISSUE TITLE
Android build fails due to dependency specification pulling in Android SDK 26 alpha

### ISSUE THREAD

**Issue by plul** [mauron85/cordova-plugin-background-geolocation#309] opened 2017-06-29 12:10 UTC
Build fails on Android, possibly due to conflicting dependencies with other Cordova plugins.

Typing `grep -rnE . -e "v4:\+"` provides me with:
```
./plugins/cordova-plugin-mauron85-background-geolocation/android/plugin/build.gradle:34:    compile 'com.android.support:support-v4:+'
./plugins/cordova-plugin-mauron85-background-geolocation/plugin.xml:24:        <framework src="com.android.support:support-v4:+" />
```

I suspect that the build failure is due to this, as it pulls in alpha versions of Android SDK 26. See here: https://github.com/dpa99c/cordova-diagnostic-plugin/issues/212

## Environment
* Project framework: Ionic 3
* Background-geolocation plugin version: 2.2.5
* Cordova Android version: 6.2.3
* Cordova version: 7.0.1

## Cordova plugins
```
com.danielsogl.cordova.clipboard 1.0.2 "Clipboard"
com.googlemaps.ios 2.2.0-fixed "Google Maps SDK for iOS"
cordova-plugin-appminimize 1.0 "AppMinimize"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin"
cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

## Debug logs
```
Error: /home/metafeta/Projects/getQueried/what/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/metafeta/Projects/getQueried/what/platforms/android/AndroidManifest.xml:27:9-31 Error:
	Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.
```

**Comment by albe** [comment] 2017-08-22 14:18
I can verify.
The issue is indeed the unspecified `"com.android.support:support-v4:+"` version, this needs to be changed to `"com.android.support:support-v4:23.+"` and everything works again.

**Comment by mauron85** [comment] 2017-11-21 06:23
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Closed by mauron85** 2017-11-21 06:23 UTC
