### ISSUE TITLE
[Question] Necessary permission for background on iOS

### ISSUE THREAD

**Issue by franciscofsales** [mauron85/cordova-plugin-background-geolocation#117] opened 2016-07-15 18:29 UTC
## Your Environment

* Plugin version:
* Platform: iOS
* Device manufacturer and model: iPhone 5s
* Cordova version (`cordova -v`): 6.2.0
* Cordova platform version (`cordova platform ls`):   ios 4.1.0
* Plugin configuration options: 
`options = {
        desiredAccuracy: 0,
        stationaryRadius: 10,
        distanceFilter: 10,
        debug: false,
        stopOnTerminate: true,
        saveBatteryOnBackground: false,
        stopOnStillActivity: false,
        startForeground: true,
        activityType: 'AutomotiveNavigation'
      };
`

## Context
If the permission is set to "While using the App", if I put the app on background, the top bar is blue and saying that my app is using location services, however, the callback is never called.

If the permission is set to "Always", the top bar doesn't get the notice but the callback is called.

## Question
Is the "Always" permission necessary or am I doing something wrong to not get the callback fired with the "While using the App"?. I see other apps with the blue notice and getting location, even with the "While using the App" permission. Thanks

**Comment by mauron85** [comment] 2016-07-16 18:06
Your problem seems like duplicate of #103

**Closed** 2016-07-16 18:06 UTC
Labels: duplicate, question
