### ISSUE TITLE
ios- location interval not working properly. 

### ISSUE THREAD

**Issue by aaronharper123** [mauron85/cordova-plugin-background-geolocation#442] opened 2018-06-06 14:03 UTC
i set interval and fastestInterval 120000 milliseconds but location updates in 15 sec - some time 20 or 10 seconds when i am walking with mobile.
I want to get location at every 120000 seconds.
 
## Your Environment

* Plugin version: 2.3.5
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer and model: iPhone 5s
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin configuration options: 
let config = {
         desiredAccuracy: 0,
         stationaryRadius: 50,
         distanceFilter: 50,
         notificationTitle: 'XYZ',
         notificationText: 'ENABLED',
         foregroundService: true,
         debug: true,
         locationProvider: 1,
         interval: 120000,
         fastestInterval: 120000,
         url: 'http://....',
         httpHeaders: {
          "Content-Type": "application/json"
        },
        postTemplate: {
            "UserId": this.UserId,
            "LocationData": [
            {
              "Lat": this.lat,
              "Long": this.lng,
              "Date": this.cuuDate,
              "BatteryPerc": this.batteryLevel
            }
            ]
        },
         method: 'POST',
         autoSync: true,
         saveBatteryOnBackground: false,
         stopOnTerminate: false,
         startOnBoot: true
     };
* Link to your project:

**Comment by mauron85** [comment] 2018-06-06 14:09
Interval and fastInterval are android only. iOS doesn't have concept of intervals.

**Comment by mauron85** [comment] 2018-06-06 14:10
Duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/393 Closing

**Closed by mauron85** 2018-06-06 14:10 UTC

**Comment by aaronharper123** [comment] 2018-06-07 05:07
@mauron85 
I am testing app in forground i.e when app is running ,
i set interval 120000 seconds but when device is stay at one side then it is automatically updates location in 10-15 seconds.
and also that,

`this.backgroundGeolocation.getValidLocations().then((res)=>{
   // array = res;
});`

above method is fires two times at many times thats why i get location with time with 2-3 times with same entry. So please tell me when am i doing wrong.
