### ISSUE TITLE
Plugin crashes the App in Android platform 

### ISSUE THREAD

**Issue by yadutechnologies** [mauron85/cordova-plugin-background-geolocation#262] opened 2017-02-18 08:35 UTC
## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: Android 6
* Device manufacturer and model: Asus Selfie
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`):  android 6.0.0
* Plugin configuration options: 

`{`
`            desiredAccuracy: 100, `
`            stationaryRadius: 100, `
`            distanceFilter: 100, `
`            maxLocations: 1000, `
`            stopOnTerminate: false, `
`            // Android only section`
`            locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,`
`            interval: 60000,`
`            fastestInterval: 5000,`
`            activitiesInterval: 10000, `
`            notificationTitle: "Nearby promotions notifications active.", `
`            notificationText: "We will notify you of nearby promotions.", `
`            notificationIconColor: "#002661", `
`            notificationIconSmall: "icon_small", `
`            notificationIconLarge: "icon_large",`
`            // iOS only`
`            pauseLocationUpdates: false`
`        }`

## Context

I have build an app which was working as expected with your plugin but after update in Android studio it crashes the app.
When I install the app with this plugin it always says "Unfortunately [App name] has stopped".
Without your plugin the app runs as expected.
Please help.

## This is what I have in Android SDK Manager
![screen shot 2017-02-18 at 1 45 26 pm](https://cloud.githubusercontent.com/assets/19183024/23091637/a4df6afc-f5e0-11e6-9574-7d9cf09e6ebd.png)

## Steps to Reproduce

1. Build app with your plugin
2. Configure your plugin and call the function `backgroundGeolocation.start();`
3. It will crash the app with message "Unfortunately [App name] has stopped"

## Debug logs

This is the logcat output. 
App ID is com.sirkle.app
[logcat.txt](https://github.com/mauron85/cordova-plugin-background-geolocation/files/784879/logcat.txt)

**Comment by klaus-donnert** [comment] 2017-02-19 16:46
I use phonegap so that I have only one codebase for both iOS and Android.
My workaround is to use cordova cli-6.3.0 and plugin version 2.2.4

**Comment by yadutechnologies** [comment] 2017-02-20 05:13
@klaus-donnert I tried plugin version 2.2.4 this morning but still not working :(

**Comment by gustavo-iniguez-goya** [comment] 2017-03-19 08:41
hey @yadutechnologies,

are you sure that the problem is linked to this plugin?

according to this stacktrace it is not:
02-18 13:58:59.587  4170  4352 V PushPlugin: execute: senderID=662927652806
02-18 13:58:59.613  4170  4352 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
02-18 13:58:59.613  4170  4352 E AndroidRuntime: Process: com.sirkle.app, PID: 4170
02-18 13:58:59.613  4170  4352 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
02-18 13:58:59.613  4170  4352 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw; or its super classes (declaration of 'com.google.android.gms.common.util.zzw' appears in /data/app/com.sirkle.app-2/base.apk)
02-18 13:59:16.288  4485  4551 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
02-18 13:59:16.288  4485  4551 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
02-18 13:59:16.288  4485  4551 E AndroidRuntime: 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:74)
(same stack at 02-18 13:59:16.288 ).

Post just the exact exception stack please. That would ease the debugging.

**Comment by mauron85** [comment] 2017-03-19 08:50
>AndroidRuntime: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw

I agree with @gustavo-iniguez-goya. It doesn't seems that is caused by this plugin directly.
I've seen this kind of errors, when you have multiple cordova plugins using different versions of native libraries (like google play ...).

**Comment by mauron85** [comment] 2017-03-19 08:51
@yadutechnologies Please post full list of cordova plugins you're using.

**Comment by yadutechnologies** [comment] 2017-03-20 15:25
sudo ionic plugin add cordova-plugin-actionsheet@2.2.2 --save; 
sudo ionic plugin add cordova-plugin-compat@1.0.0 --save; 
sudo ionic plugin add cordova-plugin-datepicker@0.9.3  --save; 
sudo ionic plugin add cordova-plugin-device@1.1.2 --save; 
sudo ionic plugin add cordova-plugin-device-motion@1.2.1 --save; 
sudo ionic plugin add cordova-plugin-device-orientation@1.0.3 --save; 
sudo ionic plugin add cordova-plugin-file@4.2.0 --save; 
sudo ionic plugin add cordova-plugin-file-transfer@1.5.1 --save; 
sudo ionic plugin add cordova-plugin-geolocation@2.2.0 --save; 
sudo ionic plugin add cordova-plugin-inappbrowser@1.4.0 --save; 
sudo ionic plugin add cordova-plugin-network-information@1.2.1 --save; 
sudo ionic plugin add cordova-plugin-splashscreen@3.2.2 --save; 
sudo ionic plugin add cordova-plugin-whitelist@1.2.2 --save; 
sudo ionic plugin add cordova-plugin-x-socialsharing@5.1.1  --save; 
sudo ionic plugin add cordova.plugins.diagnostic@3.3.2 --save;
sudo ionic plugin add phonegap-plugin-push@1.8.4 --save --variable SENDER_ID=xxxxxx; 
sudo ionic plugin add uk.co.workingedge.phonegap.plugin.launchnavigator@3.1.1 --save;
sudo ionic plugin add cordova-plugin-console@1.0.4 --save;


#removed from project, after removing it build it successfully.
#sudo ionic plugin add cordova-plugin-mauron85-background-geolocation@2.2.5 --save;

**Comment by yadutechnologies** [comment] 2017-03-20 15:26
Above is the list of plugins with there version used in the app.

**Comment by mauron85** [comment] 2017-03-20 17:32
First small advice (playing smart ass I know :-)). Try to avoid installing plugins with sudo, it's not good idea (but maybe you have good reason).

Back to your problem. The list of plugins is quite long. I would suspect collision between plugins that are using google play services. Cannot be 100% sure, which are using google play, but my guess would be:
cordova-plugin-device-motion
cordova-plugin-geolocation
phonegap-plugin-push

Try to remove those and cordova-plugin-mauron85-background-geolocation and check if your project compiles.

**Comment by gustavo-iniguez-goya** [comment] 2017-03-20 21:10
The stacktrace of the error is practically the same than this one:
https://stackoverflow.com/a/41140199

Besides what  mauron85 has said, check that answer (and the accepted one) and see if it helps you. Good luck :)

**Comment by abner-serafim** [comment] 2017-03-27 21:48
I resolved with an update of the "phonegap-plugin-push", because "phonegap-plugin-push" updated from "com.google.android.gms:play-services-gcm:9.8+" to "com.google.android.gms:play-services-gcm:10.2+" and resolved

**Comment by stephenandrews** [comment] 2017-03-30 11:58
Bah just figured the above out as well: https://github.com/phonegap/phonegap-plugin-push/issues/1588

**Comment by yadutechnologies** [comment] 2017-03-31 06:18
@abner-serafim I have changed the build.gradle file as you suggested but while building the app the build.gradle file reverted back to its original state.
![screen shot 2017-03-31 at 11 47 25 am](https://cloud.githubusercontent.com/assets/19183024/24538600/df6e5dda-1607-11e7-81fd-3f613b3da177.png)

**Comment by yadutechnologies** [comment] 2017-03-31 06:28
I have this code in config.xml file after adding the plugin, do I need to change anything over here.
![screen shot 2017-03-31 at 11 57 30 am](https://cloud.githubusercontent.com/assets/19183024/24538869/59919504-1609-11e7-93bd-7fb932eacca1.png)

**Comment by stephenandrews** [comment] 2017-03-31 06:52
Edit **platforms/android/project.properties** and change "com.google.android.gms:play-services-gcm:9.8+" to "com.google.android.gms:play-services-gcm:10.2+"

**Comment by yadutechnologies** [comment] 2017-03-31 07:11
@stephenandrews Thank the solution worked for me 👍

**Closed** 2017-03-31 07:12 UTC
Labels: waiting for input
