### ISSUE TITLE
iOS 9.1 Location Error

### ISSUE THREAD

**Issue by SaphiraT** [mauron85/cordova-plugin-background-geolocation#19] opened 2015-12-09 15:34 UTC
Background service of the plugin does not work correctly on iOS 9.1 (ipad 3). 

Pressing the "btn-home" in footer, shows the current location on map. Location privileges to app are granted "always":   

When the app is closed and running in background, there are no notifications and the map "jumps" to the current location, when its reopened.

I have also tried iOS emulator with iOS 9.0 and its working fine.

**Comment by mauron85** [comment] 2015-12-09 16:24
Can somebody else confirm this?

**Comment by mauron85** [comment] 2015-12-09 17:51
@SaphiraT I cannot reproduce your issue on ios simulator. Just checked both ios 9.2 and 9.0 with SampleApp and everything run fine.

Can you test SampleApp from example dir? 
See doc https://github.com/mauron85/cordova-plugin-background-geolocation/tree/master/example/SampleApp

**Comment by mauron85** [comment] 2015-12-28 20:59
@SaphiraT is this still relevant?

**Comment by freezyfridge** [comment] 2016-01-14 05:50
i'm tested in real devices ios 9.2 with the SampleApp. It is not working. Do we need another plugin to works in ios?

**Comment by mauron85** [comment] 2016-01-18 10:43
Seems like duplicate of #26 Need to investigate on this one

**Comment by mauron85** [comment] 2016-01-28 23:32
Hi, can plz try 0.9.2 if it resolve your issue? It's already in npm.

**Comment by mauron85** [comment] 2016-01-29 21:13
Can you confirm still having issues with 0.9.3 version of the plugin?

**Comment by mauron85** [comment] 2016-02-03 16:06
Closing for no response.

**Closed by mauron85** 2016-02-03 16:06 UTC
Labels: bug, duplicate
