### ISSUE TITLE
How disable notifications in Android?

### ISSUE THREAD

**Issue by adrieldubemarante** [mauron85/cordova-plugin-background-geolocation#161] opened 2016-09-12 20:41 UTC
We need to disable background-geolocation notification message.
Can the API provide a configuration variable to disable notification?

##  Environment
* Platform: Android

## Expected Behavior

 Disable notification message

**Comment by eakkew** [comment] 2016-09-13 05:40
I think you cannot as described in document https://github.com/mauron85/cordova-plugin-background-geolocation/wiki/Android-implementation

**Comment by mauron85** [comment] 2016-09-13 07:29
You can disable with option `startForeground`: false

**Comment by mauron85** [comment] 2016-09-13 07:30
Duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/74

**Closed** 2016-09-19 09:40 UTC
Labels: duplicate, question

**Comment by smchae** [comment] 2017-05-18 00:29
@mauron85 Thank you for this amazing plugin. I understood I could remove notification bar using `startForeground: false`. However, according to doc, `If false **location service will not be started in foreground** and no notification will be shown.` Does this mean tracking GPS stops while the user is in foreground? Or does it just means that notification bar does not start? I would like to track the user's location both in foreground and in background.
