### ISSUE TITLE
Unable to start service Intent on calling BackgroundGeolocation.start()

### ISSUE THREAD

**Issue by Amsvartner** [mauron85/cordova-plugin-background-geolocation#549] opened 2019-02-04 09:25 UTC
## Your Environment

* Plugin version: 3.0.0-alpha.50
* Platform: Android
* OS version: 8.1 (API 27)
* Device manufacturer and model: Nexus 5X

* Running in Simulator: Yes
* Cordova version: 8.1.2
* Cordova platform version: 7.1.4 (Android)

## Context

Using the example code provided, the GPS tracking doesn't initialize properly and cannot be used.

## Expected Behavior

The GPS tracking service should start, and the foreground notification in the top drawer should be visible.

## Actual Behavior

Nothing happens, the service isn't started. Foreground notification does not appear (but the events for background mode triggers in the console.log)

## Possible Fix

There has been changes to background mode, and how you start Intents, in Android 8.0+
https://developer.android.com/about/versions/oreo/background

The following issue in the react-native project may be of interest:
https://github.com/mauron85/react-native-background-geolocation/issues/172

## Debug logs

```
02-04 09:04:57.034  5194  5270 I com.marianhello.bgloc.BackgroundGeolocationFacade: Initializing plugin
02-04 09:04:57.082  5194  5270 D com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin: Registering event listeners
02-04 09:04:57.109  5194  5270 W PluginManager: THREAD WARNING: exec() call to BackgroundGeolocation.addEventListener blocked the main thread for 27ms. Plugin should use CordovaInterface.getThreadPool().
02-04 09:04:57.117  5194  5230 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-04 09:04:57.362  5194  5194 D SystemWebChromeClient: file:///android_asset/www/plugins/cordova-plugin-android-softinputmode/www/interface.js: Line 3 : Success
02-04 09:04:57.362  5194  5194 I chromium: [INFO:CONSOLE(3)] "Success", source: file:///android_asset/www/plugins/cordova-plugin-android-softinputmode/www/interface.js (3)
02-04 09:04:57.462  5194  5272 D com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO: Configuration persisted with rowId = 1
02-04 09:04:57.466  5194  5272 D com.marianhello.bgloc.BackgroundGeolocationFacade: Service configured with: Config[distanceFilter=50 stationaryRadius=100.0 desiredAccuracy=0 interval=3000 fastestInterval=5000 activitiesInterval=10000 isDebugging=true stopOnTerminate=true stopOnStillActivity=true startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=1 nTitle=PolarFleet GPS tracking nText=enabled nIconLarge= nIconSmall= nIconColor= url=myUrl Threshold=100 httpHeaders={Content-Type=application/json} maxLocations=1 postTemplate={"heading":"@bearing","foo":"bar","lon":"@longitude","id":"ADG198","lat":"@latitude","speed":"@speed","timestamp":""}]
02-04 09:04:57.490  5194  5251 D EGL_emulation: eglMakeCurrent: 0xa9205d80: ver 3 0 (tinfo 0x9563a050)
02-04 09:04:57.508  1638  1941 W ActivityManager: Unable to start service Intent { cmp=myApp/com.marianhello.bgloc.service.LocationServiceImpl (has extras) } U=0: not found
```

**Comment by mauron85** [comment] 2019-02-04 09:35
>It is the exact same problem as has been posted and fixed in the react-native project:
mauron85/react-native-background-geolocation#172

if it's exactly same problem, then it was already merged here somewhere before alpha.50.

**Comment by Amsvartner** [comment] 2019-02-04 09:40
That's not very helpful :)

**Comment by Amsvartner** [comment] 2019-02-04 09:42
That doesn't give me much to go on in trying to solve the problem. I am using the latest version of this plugin and I can't get it to work.

**Comment by int128fly** [comment] 2019-02-04 21:07
I have the exact same issue, my cordova and android version is the exact same as @Amsvartner but I am using ionic (shouldn't matter). The issue isn't with the .start() but .configure() anything below it is not getting executed like there were an error or something but the app don't crash. 

~~~
import { Component } from '@angular/core';
import { Platform, AlertController } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { HomePage } from '../pages/home/home';
import { BackgroundGeolocation, BackgroundGeolocationConfig, BackgroundGeolocationResponse } from '@ionic-native/background-geolocation/ngx';
import { LocalNotifications } from '@ionic-native/local-notifications';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(public platform: Platform, 
              public statusBar: StatusBar, 
              public splashScreen: SplashScreen,
              protected backgroundGeolocation: BackgroundGeolocation,
              protected alert: AlertController,
              private localNotifications: LocalNotifications) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();

      console.log('pre-initializing everything! <--------------------------------------------------------------');

      const config: BackgroundGeolocationConfig = {
        desiredAccuracy: 1000,
        locationProvider: 1,
        stationaryRadius: 50,
        distanceFilter: 50,
        notificationTitle: 'Background tracking',
        notificationText: 'enabled',
        debug: true,
        interval: 10000,
        fastestInterval: 5000,
        activitiesInterval: 10000,
      };
  
      this.backgroundGeolocation.configure(config)
        .subscribe((location: BackgroundGeolocationResponse) => {
          console.log(location);

          // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
          // and the background-task may be completed.  You must do this regardless if your HTTP request is successful or not.
          // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
          this.backgroundGeolocation.finish(); // FOR IOS ONLY
        }, (error) => {
          console.log('hey something bad happened!');
          console.log(error);
        });

      console.log('hey before we start anything did configure work?');
  
      // start recording location
      this.backgroundGeolocation.start();

      console.log('hey everything should be initialized!');
  
      // If you wish to turn OFF background-tracking, call the #stop method.
      //this.backgroundGeolocation.stop();
    });
  }
}
~~~

~~~
D/SystemWebChromeClient: http://localhost/build/vendor.js: Line 134709 : Ionic Native: deviceready event fired after 1433 ms
I/chromium: [INFO:CONSOLE(134709)] "Ionic Native: deviceready event fired after 1433 ms", source: http://localhost/build/vendor.js (134709)
D/SystemWebChromeClient: http://localhost/build/main.js: Line 218 : pre-initializing everything! <--------------------------------------------------------------
I/chromium: [INFO:CONSOLE(218)] "pre-initializing everything! <--------------------------------------------------------------", source: http://localhost/build/main.js (218)
D/SystemWebChromeClient: http://localhost/build/vendor.js: Line 2085 : ERROR
I/chromium: [INFO:CONSOLE(2085)] "ERROR", source: http://localhost/build/vendor.js (2085)
D/EGL_emulation: eglMakeCurrent: 0x9079a120: ver 3 0 (tinfo 0x93f07980)
~~~

**Comment by Amsvartner** [comment] 2019-02-05 07:48
I suspect that we may not have the same problem, because everything else works for me (background/foreground mode, app settings etc) but nothing happens when I call start() in the checkStatus callback:

```javascript
  BackgroundGeolocation.checkStatus(function(status) {
    console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
    console.log('[INFO] BackgroundGeolocation services enabled', status.locationServicesEnabled);
    console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);

    if (!status.isRunning) {
      BackgroundGeolocation.start(); //triggers start on start event
    }
  });
```

**Comment by int128fly** [comment] 2019-02-05 14:53
Thanks for your inputs, I've just got it working, apparently the issue was in the @ionic-native/background-geolocation/ngx 

Using the following work properly, I will create my own ionic provider at that point.
~~~
declare var BackgroundGeolocation: any;
~~~

**Comment by Amsvartner** [comment] 2019-02-08 11:33
I have skimmed through a bug report sent in from one of the app users. Here's a couple of lines of it, that might be relevant to the case.

```
Line 115527: 02-08 11:16:52.715  1000  1372  2929 I am_pause_activity: [0,133063684,net.proconx.truckapp/.MainActivity,userLeaving=true]
	Line 115531: 02-08 11:16:52.732 10077  3866  3866 I am_on_paused_called: [0,net.proconx.truckapp.MainActivity,performPause]
	Line 115533: 02-08 11:16:52.736  1000  1372  1390 I am_stop_activity: [0,133063684,net.proconx.truckapp/.MainActivity]
	Line 115537: 02-08 11:16:52.743 10077  3866  3866 I am_on_stop_called: [0,net.proconx.truckapp.MainActivity,STOP_ACTIVITY_ITEM]
	Line 115541: 02-08 11:16:52.752  1000  1372 14674 I am_crash: [3866,0,net.proconx.truckapp,952680004,android.app.RemoteServiceException,Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE),ActivityThread.java,1835]
	Line 115543: 02-08 11:16:52.754  1000  1372 14674 I am_finish_activity: [0,133063684,17308,net.proconx.truckapp/.MainActivity,force-crash]
	Line 115546: 02-08 11:16:52.756  1000  1372  1390 I am_destroy_activity: [0,133063684,17308,net.proconx.truckapp/.MainActivity,finish-imm:activityIdleInternalLocked]
	Line 115555: 02-08 11:16:58.609  1000  1372 14674 I am_destroy_activity: [0,133063684,17308,net.proconx.truckapp/.MainActivity,finish-imm:handleAppCrashedLocked]
	Lin
```

**Comment by Amsvartner** [comment] 2019-03-04 09:49
In case someone else stumbles upon this problem, I solved it by modifying LocationService.java. I replaced line 242 with the following code:

```
// Build a Notification required for running service in foreground.
String channel;

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    NotificationManager mNotificationManager = (NotificationManager)  this.getSystemService(Context.NOTIFICATION_SERVICE);

    String name = "LocationService ";
    int importance = NotificationManager.IMPORTANCE_LOW;

    NotificationChannel mChannel = new NotificationChannel("LocationService channel", name, importance);

    mChannel.enableLights(true);
    mChannel.setLightColor(Color.BLUE);

    if (mNotificationManager != null) {
        mNotificationManager.createNotificationChannel(mChannel);
    } else {
        stopSelf();
     }

    channel = "LocationService channel";

} else {
    channel = "";
}

NotificationCompat.Builder builder = new NotificationCompat.Builder(this, channel);
```

Don't forget to update your imports.


``` 
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
```

**Closed** 2019-03-04 09:52 UTC
