### ISSUE TITLE
Background Geolocation does not work under iOS

### ISSUE THREAD

**Issue by HamzaLJ** [mauron85/cordova-plugin-background-geolocation#324] opened 2017-08-22 20:06 UTC
I am using Ionic framework to develop my app, I've followed the documentation, everything works fine on Android; however on iOS it shows the blue bar that says that the app is tracking the current location on the background (only for the first 40 seconds), then that blue bar disappears and the app stop tracking the current location.

## Your Environment
* Plugin version: cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
* Platform: **iOS**
* OS version: iOS 10
* Device manufacturer / model: iPhone 6
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):  ios 4.4.0
* Plugin config

## Expected Behavior
It should track the user current location in iOS even if the app goes to the background.

## Actual Behavior
When going to the background, it shows the blue bar that says that the app is taking the current location on the background (only for the first 40 seconds), then that blue bar disappears and stop tracking the current location.

On the other hand, I have the same code working perfectly on Android devices, so I guess that there is an issue with the iOS.

## Steps to Reproduce

Just follow the documentation on the following link : https://ionicframework.com/docs/native/background-geolocation/

Then run the app under iOS

## Context
Track drivers location and update the database of the current driver location each 10 seconds.

**Comment by arapocket** [comment] 2017-08-27 22:49
Same problem. Other people have been having running into the same issue as well.

**Comment by gregor-srdic** [comment] 2017-09-10 14:45
I am also experiencing problems with tracking location after the app has been closed. Any new clues about this?

**Comment by arapocket** [comment] 2017-09-10 15:29
@gregor-srdic Yeah, this repo is no longer supported. There is a much better, working plugin here:
https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by gregor-srdic** [comment] 2017-09-11 06:04
Thanks. I managed to get this plugin working on the Android (the one you linked requires purchasing a license). I also managed to get this one working on iOS with debug mode on and some more conservative settings (larger desiredAccuracy, stationaryRadius and distanceFilter values and saveBatteryOnBackground: true) - it just returned some values after about a day of being in the background. I don't have the sim card in my iOS phone, so that might be affecting the behaviour as well.
I also prefer this plugin because it is included in the ionic native package I am working with, but if it does not work well, I will certainly try the one you linked for the iOS platform.

**Comment by laddhadhiraj** [comment] 2017-10-02 09:35
@gregor-srdic  have you find any solution for IOS? I am also facing  the same issue

**Comment by gregor-srdic** [comment] 2017-10-02 09:39
Actually I got it working, but not sure what was the solution. Could be the config:
    const config: BackgroundGeolocationConfig = {
      desiredAccuracy: 100,
      stationaryRadius: 20,
      distanceFilter: 20,
      debug: false,
      stopOnTerminate: false,
      maxLocations: 1,
      httpHeaders: { 'X-FOO': '...'},
      url: 'https://...',
      // android only
      interval: 60 * 1000,
      startOnBoot: true,
      startForeground: false,
      // iOS only
      pauseLocationUpdates: false,
      saveBatteryOnBackground: true
    };

**Comment by laddhadhiraj** [comment] 2017-10-02 13:00
@gregor-srdic it did not work :(  I think maybe this plugin is not supporting ios 11 . .. If anyone has solution for it please share me .. I just want to track in IOS when APP is killed or in background

**Comment by gregor-srdic** [comment] 2017-10-02 14:24
I haven't tested on iOS 11 yet, will let you know if it seems to work in my app ...

**Comment by s-perfilev** [comment] 2017-10-18 08:07
@laddhadhiraj, look at this fork: https://github.com/iMarvinS/cordova-plugin-background-geolocation

**Comment by laddhadhiraj** [comment] 2017-10-23 06:33
I tried it, but it not  work on app kill, I am making a app which will be
track user and also want to know if user turn off gps when app kill. , Is
it possible through this background location plugin in ionic 2

**Comment by s-perfilev** [comment] 2017-10-23 10:10
@laddhadhiraj, unfortunately, it's impossible by design iOS. Currently, I can't find doc reference, but you can start your research with https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html#//apple_ref/doc/uid/TP40009497-CH2-SW10.

**Comment by blgsyrmhnds** [comment] 2017-11-09 09:18
I have same issue with IOS background


I want to track user coordinates every 10 seconds in background so I used cordova-plugin-mauron85-background-geolocation.It works very well at the android in foreground or background but in IOS it does not work in background(it works only in foreground)

In background it does not fire success( SetLocationUpdates ) function and also it give not error,it does not fire error function.

here is my config.xml 

	```
<plugin name="cordova-plugin-mauron85-background-geolocation" source="npm" spec="2.3.2">
   
    <variable name="LOCATION_ALWAYS_USAGE_DESCRIPTION" value="Uygulama acıkken başka uygulama (navigasyon gibi) actığınızda bile servis aracınızın nerde olduğunu anlık öğrenmemiz için arka planda konumunuzu alan servise ihtiyacımız var.Onun icin GPS'i asla kapatmayınız lütfen" />
    <variable name="LOCATION_WHEN_IN_USE_USAGE_DESCRIPTION" value="Uygulama acıkken başka uygulama (navigasyon gibi) actığınızda bile servis aracınızın nerde olduğunu anlık öğrenmemiz için arka planda konumunuzu alan servise ihtiyacımız var.Onun icin GPS'i asla kapatmayınız lütfen" />
    <variable name="LOCATION_ALWAYS_AND_WHEN_IN_USE_USAGE_DESCRIPTION" value="Uygulama acıkken başka uygulama (navigasyon gibi) actığınızda bile servis aracınızın nerde olduğunu anlık öğrenmemiz için arka planda konumunuzu alan servise ihtiyacımız var.Onun icin GPS'i asla kapatmayınız lütfen" />

   
   
</plugin>
	
    <preference name="phonegap-version" value="cli-7.0.1" />
```




and here is my html page code


```
 <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
        <script type="text/javascript">

           document.addEventListener('deviceready', onDeviceReady, false);
           function onDeviceReady () {

             backgroundGeolocation.configure(SetLocationUpdates, onError, {
            desiredAccuracy: 10,
            stationaryRadius:1,
            distanceFilter: 1,
            interval: 10000
        });
         backgroundGeolocation.start();
//backgroundGeolocation.switchMode(backgroundGeolocation.mode.FOREGROUND);

         }
         }


            function onError(error) {
            alert("error:"+error.message);

        }


           function SetLocationUpdates(position){

    //store position to database via ajax call.....
```

it works very well in foreground so i try to force it to foreground in switch mode but it does not work



`backgroundGeolocation.switchMode(backgroundGeolocation.mode.FOREGROUND,switchModesuccess, switchModefail);`

**Comment by mauron85** [comment] 2017-11-09 09:26
try adding `pauseLocationUpdates: false`

**Comment by blgsyrmhnds** [comment] 2017-11-09 13:09
I added pauseLocationUpdates: false, but it still does not work in IOS in background

here is my index.html

```
    <script type="text/javascript">
	  
	   document.addEventListener('deviceready', onDeviceReady, false);
	   function onDeviceReady () {
	    var AracID = JSON.parse(localStorage.getItem("AracID"));
	   if(AracID=="-1")
	   {
	   }
	   else
	   {
	   
//
	  
	   
	   
	     var SetLocationUpdates1=function(position){	backgroundGeolocation.finish();}
	     var SetLocationUpdates=function(position){
	   var AracID = JSON.parse(localStorage.getItem("AracID"));
            var pos = {
              lat: position.latitude,
              lng: position.longitude
            };
          $.ajax({
			type: 'POST',
			url: 'http://185.59.73.82:8083/json/SetLocationUpdates',
			contentType: 'application/json; charset=utf-8',
			data: JSON.stringify({"WSUsername":"ROUTEWIX","WSPassword":"ec21FDee55B1", "AracID":AracID,"latitude": pos.lat, "longitude": pos.lng, "speed":10, "address":"istanbul"}),
			dataType: 'json',           
			success: function (data) {;},
			error: function (data) {;alert(data.ResponseText); }
		  });
		backgroundGeolocation.finish()

        }
		
		
		var  onError=function(error) {
		
		backgroundGeolocation.finish();
		playAudio();
		alert("Hata:"+error.message);
        
    }
	
	 var switchModesuccess=function() {
		playAudio();
        
    } 
	 var switchModefail=function() {
	playAudio();
	playAudio();
	playAudio();
        
    } 
	//   
	   
	   
	   
	     backgroundGeolocation.configure(SetLocationUpdates1, onError, {
        desiredAccuracy: 0,
        stationaryRadius:0,
        distanceFilter: 0,
		url: 'https://www.elevitturizm.com.tr/home/locations',
    httpHeaders: { 'X-FOO': 'bar' },
        interval: 10000,
		debug:true,
		startOnBoot: true,
		

pauseLocationUpdates: false,
saveBatteryOnBackground: true
    });
	
	
	
	
	
	
	
	
	
	
	
	


backgroundGeolocation.watchLocationMode(
  function (enabled) {
    if (enabled) {
      // location service are now enabled
      // call backgroundGeolocation.start
      // only if user already has expressed intent to start service
    } else {
      // location service are now disabled or we don't have permission
      // time to change UI to reflect that
    }
  },
  function (error) {
    alert('Error watching location mode. Error:' + error);
  }
);

backgroundGeolocation.isLocationEnabled(function (enabled) {
  if (enabled) {
    backgroundGeolocation.start(
      function () {
        // service started successfully
        // you should adjust your app UI for example change switch element to indicate
        // that service is running
      },
      function (error) {
        // Tracking has not started because of error
        // you should adjust your app UI for example change switch element to indicate
        // that service is not running
        if (error.code === 2) {
          if (window.confirm('Not authorized for location updates. Would you like to open app settings?')) {
            backgroundGeolocation.showAppSettings();
          }
        } else {
          window.alert('Start failed: ' + error.message);  
        }
      }
    );
  } else {
    // Location services are disabled
    if (window.confirm('Location is disabled. Would you like to open location settings?')) {
      backgroundGeolocation.showLocationSettings();
    }
  }
});
	
	
	
	
	
	
	
	
	
	
	 backgroundGeolocation.start();
	 backgroundGeolocation.switchMode(backgroundGeolocation.mode.FOREGROUND,switchModesuccess, switchModefail);
	 backgroundGeolocation.getLogEntries(100, printIosLogs);
	 }
	 }
	  
	  
	    
	
	
	


function playAudio() { 
	var x = document.getElementById("myAudio"); 
    x.play(); 
} 
	
	 
	  	
  </script>
```


and here is my config

<plugin name="cordova-plugin-geolocation"    source="npm" spec="2.4.1" />
	<plugin name="cordova-plugin-mauron85-background-geolocation" source="npm" spec="2.3.0">
   
    <variable name="ALWAYS_USAGE_DESCRIPTION" value="xxx" />
    
    
   
   
   
   
   
   
   
</plugin>

**Comment by blgsyrmhnds** [comment] 2017-11-09 13:25
In IOS in background mode sound is   SIRI stop listening sound
what does it mean?If client change his location in a kilometers is it get active again?
what is meaning of "Passive geolocation engaged" Is that error?Or it will get tracking after big location changed?

**Comment by blgsyrmhnds** [comment] 2017-11-09 13:51
@bharat-saralweb

**Comment by blgsyrmhnds** [comment] 2017-11-09 19:38
Hi
are there any problem with my code?What should I do?Can you give suggestion please @HamzaLJ   @gregor-srdic  @mauron85

**Comment by mauron85** [comment] 2017-11-21 06:20
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Closed by mauron85** 2017-11-21 06:20 UTC
