### ISSUE TITLE
IOS background - position changing very slowly?

### ISSUE THREAD

**Issue by tverilytt** [mauron85/cordova-plugin-background-geolocation#187] opened 2016-10-19 18:19 UTC
Hi!
This is more of a question on how to get as exact positions as possible when running in background on IOS (9.3). I do get regular position updates, but they change very slowly. Android works very well. So I wonder if someone have any hints on what to change or add?

I use these settings:

```
         desiredAccuracy : 10
         stationaryRadius : 20,  
         distanceFilter : 30,
         startForeground : false,
         interval : 60000, // Android
         locationProvider : <User can switch between both options>, // Android
         activityType : <I have tried the 4 different options>
         pauseLocationUpdates : false, // IOS
         saveBatteryOnBackground : false // IOS
```

Cheers
-jo2

**Comment by kristfal** [comment] 2016-10-24 09:44
Reduce `distanceFilter`. If that doesn't give you short enough intervals, see #185. You might want to test the PR mentioned in that issue as well.

**Comment by tverilytt** [comment] 2016-10-24 10:08
@kristfal Thanks for that, I will try that, and I also noticed #185. So will try reducing both distanceFilter and desiredAccuracy :-)

**Comment by mamartins** [comment] 2016-10-26 17:58
I can confirm. Path tracking in iOS is impossible this way

**Comment by tverilytt** [comment] 2016-10-27 08:44
I tried setting distanceFilter to 1 and desiredAccuracy to 0, but does not seem to make any difference so far...

**Comment by mamartins** [comment] 2016-10-27 09:26
which activity type should give more results? Fitness?

**Comment by srsarcasmo** [comment] 2016-10-27 15:06
It can be used in IOS version 4?

**Comment by kristfal** [comment] 2016-10-28 10:06
Use the #185 fork. It should give you updates lower than 10 m apart with the following settings:

```
          desiredAccuracy: 0,
          maxLocations: 10000,
          debug: false,
          pauseLocationUpdates: false,
          locationProvider: 1,
          distanceFilterCalculationAlgorithm: 0,
          notificationText: '',
          stopOnStillActivity: false,
          startForeground: true,
          notificationTitle: 'GPS is active',
          stationaryRadius: 5,
          distanceFilter: 1,
          interval: 1000,
          fastestInterval: 1000,
          activitiesInterval: 500,
          saveBatteryOnBackground: false,
          acitivyType: 'Fitness'
```

**Comment by mamartins** [comment] 2016-10-28 12:02
on iOS I installed instead a background job app and then I use $cordovaGeolocation to send my locations, and it works like a charm. The problem is that this not work on android because bg jobs do not have access to location...

**Comment by mamartins** [comment] 2016-10-31 10:05
even with these settings I only get 1 update every 30sec or so on iOS

**Comment by tverilytt** [comment] 2016-11-03 22:47
Has anyone tried swithMode to FOREGROUND even when running in background?

**Comment by mamartins** [comment] 2016-11-04 12:21
I haven't

**Comment by tverilytt** [comment] 2016-11-08 09:06
I tried doing switchMode til FOREGROUND, the switch itself seems to work, since the IOS device shows a blue notification line on top of screen, stating the app is using location. But does not seem to make any difference for location updates...

**Comment by coyu1314** [comment] 2017-01-19 13:57
@mamartins I use exactly the same method as you do, which using the backgroundMode to do the trick on updating the geolocation on ios. It's much more stable and consistent.  However, app store reject my submission saying that 

> Your app declares support for audio in the UIBackgroundModes key in your Info.plist but did not include features that require persistent audio.

How did you get past the stupid app store? It always give me hard time for every time when i make a submission. I can't stand with them anymore. thanks in advance.

**Comment by tverilytt** [comment] 2017-01-19 14:06
@coyu1314  Hi! I did not get the app approved by App Store with the backgrondMode plugin, so had to remove it. I replaced it with the IOS background-fetch plugin (https://github.com/transistorsoft/cordova-plugin-background-fetch). 
It is not optimal, it runs about every 15 minutes, but is adequate for the apps background data usage. For background geolocation, I use this plugin (no problem getting it approve).
The backgroundMode plugin uses background audio feature to stay alive, and since my app does not stream or use audio in the background, it was kinda hard to argue for approval...:-/

**Comment by coyu1314** [comment] 2017-01-19 14:17
@tverilytt thanks for your info. background-fetch plugin is not suitable for my case. 15mins is too long for my app. For some odd reason on ios, it is very unsable. it will stop sending location occasionally or taking too long to update a location. I already tried the config setting here. it's still kind not very stable. This is why I am hunting for an alternative solution just for the ios. thanks

**Comment by mauron85** [comment] 2017-11-21 06:49
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Closed by mauron85** 2017-11-21 06:49 UTC
