### ISSUE TITLE
app crashes on first start after install (java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference)

### ISSUE THREAD

**Issue by apptum** [mauron85/cordova-plugin-background-geolocation#268] opened 2017-02-23 10:39 UTC
after a fresh install the app crashes immediately as the plugin gets started. It runs fine from second start.

from the adb.logcat
```
E/AndroidRuntime(10266): FATAL EXCEPTION: pool-2-thread-2
E/AndroidRuntime(10266): Process: com.apptum.app, PID: 10266
E/AndroidRuntime(10266): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
E/AndroidRuntime(10266): 	at org.apache.cordova.PluginResult.<init>(PluginResult.java:55)
E/AndroidRuntime(10266): 	at org.apache.cordova.CallbackContext.success(CallbackContext.java:72)
E/AndroidRuntime(10266): 	at com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin$10.run(BackgroundGeolocationPlugin.java:408)
E/AndroidRuntime(10266): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(10266): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(10266): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  651):   Force finishing activity 1 com.apptum.app/.MainActivity
W/BroadcastQueue(  651): Skipping deliver [background] BroadcastRecord{11cf9798 u-1 android.net.conn.CONNECTIVITY_CHANGE callingPid=-1 callingUid=-1} to ReceiverList{2cf73f14 10266 com.apptum.app/10090/u0 remote:1e5ee567}: process crashing
```

Plugin version: 2.2.4
Platform: Android
OS version: 5.1
Device manufacturer and model: HTC One
Plugin configuration options:
´´´ debug: false,
desiredAccuracy: 0,
stationaryRadius: 6,
distanceFilter: 6,
stopOnTerminate: true,
startOnBoot: false,
startForeground: true,
interval: 3000,
fastestInterval: 3000,
activitiesInterval: 5000,
stopOnStillActivity: true,
stopOnStillMinAccuracy: 30
´´´

**Comment by mauron85** [comment] 2017-02-23 11:00
Seems that crash is happening while getting config. Are you calling get config, before actually configuring plugin?

**Comment by apptum** [comment] 2017-02-23 12:03
nupp, just double checked.
but I call a .getConfig immediately after .config:
```
backgroundGeolocation.configure(locationWatch.locationWatchUpdate, locationWatch.locErrorHndlr, locationWatch.backgroundGeolocationOptions);
backgroundGeolocation.getConfig(function(c){console.log("configured backgroundGeolocation with: ", c);});
```

here's a logcat. (this time from my nexus 5x with android 7.1.1)

```
02-23 12:32:03.157 19742 19742 I chromium: [INFO:CONSOLE(326)] "legalAccepted", source: file:///android_asset/www/js/main.js (326)
02-23 12:32:03.157 19742 19742 I chromium: [INFO:CONSOLE(326)] "options_sw1_expChat", source: file:///android_asset/www/js/main.js (326)
02-23 12:32:03.160 19742 19742 I chromium: [INFO:CONSOLE(326)] "options_sw2_bgTra", source: file:///android_asset/www/js/main.js (326)
02-23 12:32:03.193 19742 19742 I chromium: [INFO:CONSOLE(447)] "Firebase initialised", source: file:///android_asset/www/js/main.js (447)
02-23 12:32:03.193 19742 19742 I chromium: [INFO:CONSOLE(2663)] "inputHandler.disable", source: file:///android_asset/www/js/main.js (2663)
02-23 12:32:03.196 19742 19742 I chromium: [INFO:CONSOLE(929)] "locationWatch.init", source: file:///android_asset/www/js/main.js (929)
02-23 12:32:03.335 19742 19875 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: initializing plugin
02-23 12:32:03.353 19742 19875 D com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: Location services enabled check
02-23 12:32:03.373 19742 19877 D com.marianhello.bgloc.data.sqlite.SQLiteOpenHelper: Creating db: cordova_bg_geolocation.db
02-23 12:32:03.373 19742 19877 D com.marianhello.bgloc.data.sqlite.SQLiteOpenHelper: CREATE TABLE location (_id INTEGER PRIMARY KEY,time INTEGER,accuracy REAL,speed REAL,bearing REAL,altitude REAL,latitude REAL,longitude REAL,radius REAL,has_accuracy INTEGER,has_speed INTEGER,has_bearing INTEGER,has_altitude INTEGER,has_radius INTEGER,provider TEXT,service_provider INTEGER,valid INTEGER,batch_start INTEGER )
02-23 12:32:03.374 19742 19877 D com.marianhello.bgloc.data.sqlite.SQLiteOpenHelper: CREATE TABLE configuration (_id INTEGER PRIMARY KEY,stationary_radius REAL,distance_filter INTEGER,desired_accuracy INTEGER,debugging INTEGER,notification_title TEXT,notification_text TEXT,notification_icon_small TEXT,notification_icon_large TEXT,notification_icon_color TEXT,stop_terminate INTEGER,stop_still INTEGER,start_boot INTEGER,start_foreground INTEGER,service_provider TEXT,interval INTEGER,fastest_interval INTEGER,activities_interval INTEGER,url TEXT,sync_url TEXT,sync_threshold INTEGER,http_headers TEXT,max_locations INTEGER )
02-23 12:32:03.374 19742 19877 D com.marianhello.bgloc.data.sqlite.SQLiteOpenHelper: CREATE INDEX time_idx ON location (time)
02-23 12:32:03.375 19742 19877 D com.marianhello.bgloc.data.sqlite.SQLiteOpenHelper: CREATE INDEX batch_id_idx ON location (batch_start)
02-23 12:32:03.396 19742 19877 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
02-23 12:32:03.396 19742 19877 E AndroidRuntime: Process: com.apptum.app, PID: 19742
02-23 12:32:03.396 19742 19877 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
02-23 12:32:03.396 19742 19877 E AndroidRuntime: 	at org.apache.cordova.PluginResult.<init>(PluginResult.java:55)
02-23 12:32:03.396 19742 19877 E AndroidRuntime: 	at org.apache.cordova.CallbackContext.success(CallbackContext.java:72)
02-23 12:32:03.396 19742 19877 E AndroidRuntime: 	at com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin$10.run(BackgroundGeolocationPlugin.java:408)
02-23 12:32:03.396 19742 19877 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-23 12:32:03.396 19742 19877 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-23 12:32:03.396 19742 19877 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-23 12:32:03.397  2166 15716 W ActivityManager:   Force finishing activity com.apptum.app/.MainActivity
02-23 12:32:03.398 19742 20218 D com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO: Configuration persisted with rowId = 1
02-23 12:32:03.399 19742 20218 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: Requesting permissions from user
02-23 12:32:03.408 19742 19742 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: App will be paused multitasking=true
02-23 12:32:03.422  2166  3797 I ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10237 on display 0
02-23 12:32:03.428  2166  3797 W ActivityManager: startActivity called from finishing ActivityRecord{635a514 u0 com.apptum.app/.MainActivity t5735 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=android.content.pm.action.REQUEST_PERMISSIONS flg=0x800000 pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras) }
02-23 12:32:03.449  2166  4315 I ActivityManager: Start proc 20222:com.google.android.packageinstaller/u0a18 for activity com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity
02-23 12:32:03.491 19742 19742 I chromium: [INFO:CONSOLE(312)] "globalConfig write SUCCESS: legalAccepted: true", source: file:///android_asset/www/js/main.js (312)
02-23 12:32:03.491 19742 19742 I chromium: [INFO:CONSOLE(45)] "EVENT: PAUSE", source: file:///android_asset/www/js/main.js (45)
02-23 12:32:03.529 20222 20222 W System  : ClassLoader referenced unknown path: /system/priv-app/GooglePackageInstaller/lib/arm64
02-23 12:32:03.547  2166  9398 I OpenGLRenderer: Initialized EGL, version 1.4
02-23 12:32:03.547  2166  9398 D OpenGLRenderer: Swap behavior 1
02-23 12:32:03.567 10601 10689 I Adreno  : QUALCOMM build                   : a5b4970, If5818605d9
02-23 12:32:03.567 10601 10689 I Adreno  : Build Date                       : 10/12/16
02-23 12:32:03.567 10601 10689 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
02-23 12:32:03.567 10601 10689 I Adreno  : Local Branch                     : N24D
02-23 12:32:03.567 10601 10689 I Adreno  : Remote Branch                    :
02-23 12:32:03.567 10601 10689 I Adreno  : Remote Branch                    :
02-23 12:32:03.567 10601 10689 I Adreno  : Reconstruct Branch               :
02-23 12:32:03.606  2166  2179 I art     : Background partial concurrent mark sweep GC freed 28067(1776KB) AllocSpace objects, 23(460KB) LOS objects, 28% free, 39MB/55MB, paused 1.744ms total 133.551ms
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: No package: null
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: android.content.pm.PackageManager$NameNotFoundException
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:147)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:132)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.getCallingPackageInfo(GrantPermissionsActivity.java:354)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(GrantPermissionsActivity.java:103)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.Activity.performCreate(Activity.java:6679)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.os.Looper.loop(Looper.java:154)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-23 12:32:03.626 20222 20222 I GrantPermissionsActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-23 12:32:03.641 10601 10689 I OpenGLRenderer: Initialized EGL, version 1.4
02-23 12:32:03.641 10601 10689 D OpenGLRenderer: Swap behavior 1
02-23 12:32:04.052 19742 19742 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: App is no longer visible
02-23 12:32:04.110 19742 19742 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: Destroying plugin
02-23 12:32:04.124 19742 19742 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: Stopping bg service
02-23 12:32:04.147 19742 19742 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
```


I also noticed that `.getConfig` gives me wrong state:
I change the `locationProvider`on pause and on resume:

```
locationWatch.stop();
locationWatch.backgroundGeolocationOptions.locationProvider = 1;
backgroundGeolocation.configure(locationWatch.locationWatchUpdate, locationWatch.locErrorHndlr, locationWatch.backgroundGeolocationOptions);
backgroundGeolocation.getConfig(function(c){console.log("configured backgroundGeolocation with: ", c);});
```

but the object "c" never changes and keeps saying `locationProvider = 0`.
I just tested it with enabling debug on pause and it works correctly (it peeps), but `.getConfig` keeps saying `debug: false`.

**Comment by apptum** [comment] 2017-02-23 12:09
new "feature" :D
- added `debug = true`on pause.
- correctly starts beeping when in background.
- update code and remove `debug = true`on pause. update app via `phonegap run android`.
- first start says: `configured backgroundGeolocation with: [...] debug = true [...]`  o.O
so the config is persistent between app updates? maybe that adds to the problem?

**Comment by mauron85** [comment] 2017-02-23 12:42
yes, configuration is persisted between updates (nothing special, as config is stored in sqlitedb).

I would say, the problem is that `configure` is asynchronous so if you calling getConfig right after (or before) `configure` config may not yet be stored in sqlitedb. Try adding setTimeout before getConfig call.

**Comment by apptum** [comment] 2017-02-23 12:46
hmm, suboptimal, but thanks for the hint. I'll try the timer!
Thinking of future app updates: is there a way of manually clearing the db?

**Comment by mauron85** [comment] 2017-02-23 12:48
of course this can be improved so labeling this as an bug.

**Comment by mauron85** [comment] 2017-02-23 12:59
REMARK: the only problem fixing this is what `getConfig` should return in following situations:

1. `getConfig` is called immediately after `configure` (which runs in separate thread) so configuration is not yet stored in db, but plugin instance variable config might be already initialized. Check out [line 292](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/v2.2.4/android/plugin/src/main/java/com/tenforwardconsulting/cordova/BackgroundGeolocationPlugin.java#L292)

Possible solutions:

1. `configure` don't run in separate thread (UI will be slightly less responsive while configuring plugin)
2. add js callbacks to `configure` so getConfig can be called after configuration is done (not recommended as there are already two)
3. `getConfig` will return empty object or null

**Comment by apptum** [comment] 2017-02-24 08:06
+1 for another - optional - callback. Or promise?

**Comment by mauron85** [comment] 2018-04-02 12:01
Configuration phase was rewritten in latest alpha. It's not even necessary to call configure anymore - defaults will be used. Should be fixed by now.

**Closed by mauron85** 2018-04-02 12:01 UTC
Labels: bug, help wanted
