### ISSUE TITLE
Latest 2.2.5 version make Android builds fail on PGB (cli-6.3.0), previous versions work

### ISSUE THREAD

**Issue by FlossyWeb** [mauron85/cordova-plugin-background-geolocation#215] opened 2016-12-02 12:12 UTC
## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: Irrelevant
* Device manufacturer and model: Irrelevant
* Cordova version (`cordova -v`): 5.2.1
* Cordova platform version (`cordova platform ls`): Gradle build
* Plugin configuration options: Irrelevant
* Link to your project: https://github.com/FlossyWeb/TaxiOff

## Context
Unable to build for Android using PhoneGap Build with latest plugin version 2.2.5, version 2.2.4 is working fine.
## Expected Behavior
It should have built ;-)

## Actual Behavior
It builds just fine ;-)

## Possible Fix
?

## Steps to Reproduce
1. Get a project on PGB
2. Make it use cli-6.3.0 and gradle build
3. Insert npm plugin with version 2.2.5
4. Try to build for Android

## Context
I've just tried to update the plugin to the latest

## Debug logs
Here is the end of generated log file:
`:processX86ReleaseResources/project/res/xml/authenticator.xml:5:19-31: AAPT: No resource found that matches the given name (at 'icon' with value '@mipmap/icon').
    
/project/res/xml/authenticator.xml:6:24-36: AAPT: No resource found that matches the given name (at 'smallIcon' with value '@mipmap/icon').
    
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processX86ReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/android-sdk/build-tools/24.0.1/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.031 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/project/res/xml/authenticator.xml:5:19-31: AAPT: No resource found that matches the given name (at 'icon' with value '@mipmap/icon').
    
/project/res/xml/authenticator.xml:6:24-36: AAPT: No resource found that matches the given name (at 'smallIcon' with value '@mipmap/icon').
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processX86ReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/android-sdk/build-tools/24.0.1/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by mauron85** [comment] 2016-12-02 16:25
I think this is duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/206

**Comment by klaus-donnert** [comment] 2016-12-06 19:13
The solution is to force PGB to use the updated Cli-6.4.0 by adding 

`<preference name="phonegap-version" value="cli-6.4.0" />`

to your config.xml

**Comment by mauron85** [comment] 2017-10-31 14:55
This should be already resolved in 2.3.0.

**Closed by mauron85** 2017-10-31 14:55 UTC
Labels: duplicate
