### ISSUE TITLE
IOS location does not change

### ISSUE THREAD

**Issue by hkncnr07** [mauron85/cordova-plugin-background-geolocation#423] opened 2018-05-11 13:53 UTC
I am using the 2.2.5 version of that plugin. It is workning right at Android. But in IOS the location change occur nearly 5 or 10 minutes (callback function). But I want the get the location every 5 seconds. What is the true way to get IOS location.

* Plugin version: 2.2.5
* Platform: iOS
* OS version: 9
* Cordova version: 8.0.0
* Cordova platform version : IOS 4.5.4
* Plugin configuration options: desiredAccuracy: 20,
                                    stationaryRadius: 20,
                                    distanceFilter:20,
                                    //debug: true,
                                    stopOnTerminate: true,
                                    locationProvider: 
                                    interval: 2000,
                                    fastestInterval: 3000,
                                    activitiesInterval: 3000,
                                    stopOnStillActivity: false

## Context
At android the callback function call in given period but at IOS it does not call.

## Expected Behavior
Callback function must fire in given period

## Actual Behavior
Callback function not fire

## Steps to Reproduce

1.
2.
3.
4.

## Context
I cant get the location of IOS.

**Comment by mauron85** [comment] 2018-05-22 08:37
Duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/393

Read explanation there.

**Closed by mauron85** 2018-05-22 08:37 UTC
Labels: duplicate
