### ISSUE TITLE
iOS updates only every 30sec

### ISSUE THREAD

**Issue by mamartins** [mauron85/cordova-plugin-background-geolocation#198] opened 2016-10-31 14:33 UTC
The iOS app only sends locations to server (only 1 at a time) every 30 seconds, android works fine.

## Your Environment

* Plugin version: 2.2.3
* Platform: iOS 
* OS version: 9.3 and 10.1
* Device manufacturer and model: iPhone 5s and iPhone 7
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): ios 4.3.0
* Plugin configuration options: 
                httpHeaders: {
                    'Authorization': token
                },
                url: URL_DELIVERY_POSITION.UPDATE
                desiredAccuracy: 0,
                maxLocations: 100,
                debug: true,
                pauseLocationUpdates: false,
                locationProvider: 1,
                distanceFilterCalculationAlgorithm: 1,
                notificationText: '',
                stopOnStillActivity: false,
                startForeground: true,
                notificationTitle: 'GPS is active',
                stationaryRadius: 40,
                distanceFilter: 10,
                interval: 1000,
                fastestInterval: 1000,
                activitiesInterval: 500,
                saveBatteryOnBackground: false,
                acitivyType: 'Fitness'

## Context
I only get updates to my server being the app in foreground or background every 30s. Watching the logs it seems that the locations are saved on the DB but not posted to my server. 
Logging getValidLocations() also show much more locations than the ones sent to me.

## Expected Behavior
on location detection get the update

## Actual Behavior
every 30 sec

## Possible Fix
I found the code that restarts the bgTask on locationManager.m line 338. If i change the 30 to other number I get the updates every x seconds I set there.

**Comment by bryanterrell** [comment] 2016-10-31 19:16
I am experiencing the same thing and also noticed that changing the 30 seconds changed the update frequency.

I ended up getting updates to occur about as frequently as when in the foreground by removing this return statement:

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/ios/CDVBackgroundGeolocation/LocationManager.m#L394

This works if I have the debugger attached to a device and I'm simulating the location with a GPX file, but if I use it in a real world scenario I think the app maybe be getting killed after some time (a few minutes maybe - haven't tested enough to know yet).

The return statement seems like it will prevent any updates except for the one that occurs right after the background task is killed and started up again, but I may be wrong (I don't do much Obj C).

Wondering if the app is getting killed if it's because the BG tasks that are now getting created (the code runs right after the return statement) need to be stopped after the POST occurs. Haven't had a chance to test that yet.

**Comment by marvi14** [comment] 2016-12-17 15:35
@mamartins I changed the line to this

if (-[lastBgTaskAt timeIntervalSinceNow] > 0.1)

Even though the updates are thrown more frequently (like 7,8 seconds)...i can't manage to make them be like 1 or 2 seconds...how frequent do you accomplish to receive updates?

**Comment by bryanterrell** [comment] 2016-12-20 16:44
@marvi14, in case you're interested, I was able to get ~1 second updates with some changes in this fork:
https://github.com/37d/cordova-plugin-background-geolocation.git#f937ba299ba84097efa15cf0cff3071e9d49217d

**Comment by marvi14** [comment] 2016-12-20 17:28
@bryanterrell hi! I also try removing that "return" statement, but the result was the same. I will try changing my LocationManager.m for yours and see what results i achive!

**Comment by mamartins** [comment] 2016-12-26 09:48
@marvi14 I did that and with mock locations and with speeds of 90/100km/h I was getting 1,2 sec and in real world with lower car speed I too only have updates every 7/8 sec. We decided that this is enough close for our purpose but if you find a way do reduce this time please let me know!

**Comment by marvi14** [comment] 2016-12-26 22:34
@mamartins with @bryanterrell LocationManager.m, I get ~5 secs updates in the device...that's the best I can achive. I'm really needing to improve that to 1~2 secs, but I don't know what else to do

**Comment by marvi14** [comment] 2016-12-28 00:00
@mamartins @bryanterrell @mauron85 I have a clue, but i'm not being able to making it work...when you switch mode, from BG to FB or from FG to BG, the next 2,3 udpdates, are in like 1/2 secs. After that, they keep on coming in 5 secs aprox. Do you have any idea why? If we can reproduce that behaviour programatically, we can achive what we want

**Comment by mauron85** [comment] 2016-12-28 07:30
@marvi14  Switching from BG/FG causes plugin to start location sampling. Location sampling basically sets very high accuracy (zero) and zero timeout for period of up to 30s to get best possible location. That is the reason you see burst of location when switching from FG/BG.

But to be honest, I feel that both iOS and Android implementation can be much better. I need to take new look at it.

**Comment by marvi14** [comment] 2016-12-28 12:40
@mauron85 even though it could be better, in Android i´m getting 1/2 secs updates, so it´s fair enough to any kind of application. But in iOS the best i could achive is 4/5 secs, and for a driving app it´s a big gap, so 1/2 secs like in Android is essential.

I will keep on trying, modifying the LocationManager.m in order to get that. I´ll keep you updated about any progress I make. Do the same for me please.

Regards

**Comment by mauron85** [comment] 2017-11-21 06:49
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Closed by mauron85** 2017-11-21 06:49 UTC
