### ISSUE TITLE
Plugin not sending notifications from platform 6.3.0 in Android 8

### ISSUE THREAD

**Issue by paulsynth** [mauron85/cordova-plugin-background-geolocation#354] opened 2017-12-04 10:03 UTC
## Your Environment

* Plugin version: 2.3.2
* Platform: Android
* OS version: 8.0
* Device manufacturer and model: LG Nexus 5x / Samsung J7 2017
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 6.3.0

## Context

We've tested out Ionic 1 and Ionic 3 apps in many devices and different Android versions. The scenario is:

- The default version of the android plaftorm that Cordova installed by default is 6.3.0.
- Our Ionic 1 apps and new Ionic 3 ones worked well in every version of Android < 8.0.0
- Our Ionic 1 apps worked well even in Android 8.0.0

## Expected Behavior

When start sending position with BackgroundGeolocation start function, a new resident notification should appear even when the app is started or not. The only thing that happens correctly is the position is being sent correctly.

## Actual Behavior

There's no notification at all.  

## Possible Fix

The only thing we guess is there's something changed in version 6.3.0 that override or extends the functionality of the previous android platforms and Android 8 is not taking into account. 

## Steps to Reproduce

1. Install Android 8
2. Deploy an app that has been deployed witi android 6.3.0 platform
3. Go to a section wherever the backgroundgeolocation has to be started, or force by console the call by using breakpoints.
4. You will not see the notification, but the position is being sent correctly. 

## Context

Our customers cannot be sure the backgroundgeolocation position is being sent and they are worry even if the app is on the front or in the background.

## Debug logs

There's no messages in the log at all, so it seems nothing indicates an error is being thrown.

**Comment by paulsynth** [comment] 2018-02-07 23:15
Do you think is an affordable issue? We're requesting plugins whose minimal required platform is Android@6.3.0 and we cannot get rid of your plugin, so we're in an embarrassing situation. Thanks so much!

**Comment by mauron85** [comment] 2018-02-08 05:58
Is this related to Android 8 or cordova-android 6.3.0?

**Comment by paulsynth** [comment] 2018-02-08 12:40
Is actually a combination of both versions, so I'm afraid it may be happening with above versions because a short time ago, I installed cordova-android 6.4.0 and no way. To summarize, for the sake of the apps can be working after an Android update, we're using cordova-android 6.2.0 in order to your plugin go on working, with the desire we can use cordova-android 6.3.0 or above. Thanks!

**Comment by Chal131313** [comment] 2018-03-07 13:41
I found a solution, so maybe it can be solved by mauron by adding this to the plugin. In a test project i added the notification channels (the Android O convention) to the place where te notification is build.

btw i'm using:
Plugin version: 2.3.3
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): android 6.3.0
Device: Galaxy S8 with Android O, Emulator with Android O, Galaxy S6 without Android O

Before this solution the notifications where not working on the S8 and the emulator. They did on the S6

```
NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
builder.setContentTitle(config.getNotificationTitle());
builder.setContentText(config.getNotificationText());

......

PendingIntent contentIntent = PendingIntent.getActivity(context, 0, launchIntent, PendingIntent.FLAG_CANCEL_CURRENT);
            builder.setContentIntent(contentIntent);

// -- start notification channels, this is the part to add
NotificationManager mNotificationManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
String CHANNEL_ID = "background_location";
// Android O requires a Notification Channel.
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
  CharSequence name = getString(R.string.app_name);
  // Create the channel for the notification
  NotificationChannel mChannel =
    new NotificationChannel(CHANNEL_ID, name, NotificationManager.IMPORTANCE_DEFAULT);

  // Set the Notification Channel for the Notification Manager.
  mNotificationManager.createNotificationChannel(mChannel);
  builder.setChannelId(CHANNEL_ID); // Channel ID
}
// -- end notification channels

Notification notification = builder.build();
notification.flags |= Notification.FLAG_ONGOING_EVENT | Notification.FLAG_FOREGROUND_SERVICE | Notification.FLAG_NO_CLEAR;
startForeground(startId, notification);
```

For me it is showing the notification now, on all of the earlier named devices. It's not the best way of solving it for me, because it's not in the plugin, but maybe as i said earlier, Mauron can add this and test it. I don't really have the time for it to fully test it on more devices, then the ones i own.

Btw, i was checking if react native worked, and it seems that there are no problems with the notification on react native on a device with Android O, even though the code is kinda the same and doesnt have the channels.

**Comment by mauron85** [comment] 2018-03-08 16:04
I merged @Chal131313 changes. Can you plz try:

`npm i cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.15-oreo.1`

**Comment by Chal131313** [comment] 2018-03-09 09:15
@mauron85 I have tested it with the same devices as i used earlier. I can confirm that it works. 

There were some problems with using it, because i'm using it with ionic (ionic didn't recognized the plugin, probably because of the "3.0.0-alpha.15-oreo.2", and i didn't knew how to solve that. But i got it working by just directly calling the cordova plugin, and then it works fine and most important, it's showing the notification

**Comment by Chal131313** [comment] 2018-03-09 09:22
Hmm, little correction. It seems that the notification closes itself when the app is closed. Don't know if thats my fault or the plugins fault

**Comment by Chal131313** [comment] 2018-03-09 09:26
Ok, i found out it was my fault. Forgot to configure it to don't stop at terminate.

**Closed** 2018-04-21 13:11 UTC
Labels: android, enhancement
