### ISSUE TITLE
RuntimeException while using the plugin in debug mode. 

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [mauron85/cordova-plugin-background-geolocation#253] opened 2017-01-21 11:46 UTC
I've seen this problem while using the plugin in debug mode.

>java.lang.RuntimeException: Method called after release()
> android.media.ToneGenerator.startTone(Native Method)
> com.marianhello.bgloc.AbstractLocationProvider.startTone(AbstractLocationProvider.java:143)

## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: android 5/6
* Device manufacturer and model:
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 6.0.0
* Plugin configuration options: debug: true
* Link to your project:

## Possible Fix

At AbstractLocationProvider.java:143 change this:
>        toneGenerator.startTone(tone, duration);
by:
>       if (toneGenerator != null){
>           toneGenerator.startTone(tone, duration);
>       }

## Steps to Reproduce

1. Configure the plugin with dbeug: true, and start receiving locations.

## Context

It crashed the app.

## Debug logs

> java.lang.RuntimeException: Method called after release()
>12-12 09:30:41.310  2179  3120 E AndroidRuntime:           at android.media.ToneGenerator.startTone(Native Method)
>12-12 09:30:41.310  2179  3120 E AndroidRuntime:           at com.marianhello.bgloc.AbstractLocationProvider.startTone(AbstractLocationProvider.java:143)
>12-12 09:30:41.310  2179  3120 E AndroidRuntime:           at com.marianhello.bgloc.ActivityRecognitionLocationProvider.onLocationChanged(ActivityRecognitionLocationProvider.java:83) java.lang.RuntimeException: Method called after release()
>12-12 09:30:41.310  2179  3120 E AndroidRuntime:           at android.media.ToneGenerator.startTone(Native Method)
>12-12 09:30:41.310  2179  3120 E AndroidRuntime:           at com.marianhello.bgloc.AbstractLocationProvider.startTone(AbstractLocationProvider.java:143)
>12-12 09:30:41.310  2179  3120 E AndroidRuntime:           at com.marianhello.bgloc.ActivityRecognitionLocationProvider.onLocationChanged(ActivityRecognitionLocationProvider.java:83)

**Comment by gustavo-iniguez-goya** [comment] 2017-03-23 23:32
Hi,

I've got reports of the same problem but a different point of the source:

Caused by java.lang.RuntimeException: Init failed
android.media.ToneGenerator.native_setup (ToneGenerator.java)
android.media.ToneGenerator.<init> (ToneGenerator.java:746)
com.marianhello.bgloc.AbstractLocationProvider.onCreate (AbstractLocationProvider.java:52)
com.marianhello.bgloc.ActivityRecognitionLocationProvider.onCreate (ActivityRecognitionLocationProvider.java:50)
com.marianhello.bgloc.LocationProviderFactory.getInstance (LocationProviderFactory.java:43)
com.marianhello.bgloc.LocationService.onStartCommand (LocationService.java:236)

For now I've surrounded the onCreate() and onDestroy() methods with a try{}catch().

**Comment by mauron85** [comment] 2017-11-21 06:41
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Closed by mauron85** 2017-11-21 06:41 UTC

**Comment by ThorvaldAagaard** [comment] 2018-09-07 19:40
I have just seen the same problem in the latest version of the plugin 3.0.0-alpha.41 where I get this error
```
     Caused by: java.lang.RuntimeException: Init failed
        at android.media.ToneGenerator.native_setup(Native Method)
        at android.media.ToneGenerator.<init>(ToneGenerator.java:863)
        at com.marianhello.bgloc.provider.AbstractLocationProvider.onCreate(AbstractLocationProvider.java:52)
        at com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider.onCreate(DistanceFilterLocationProvider.java:83)
        at com.marianhello.bgloc.LocationService.onStartCommand(LocationService.java:261)
```

This error makes my application stop, and interesting it does not happen instantly but typically after using the app for some period

I have debug=false, so I expect no sound at all.

I think the error can be caused by switching between foreground and background

This is in the log just prior to the crash

```
09-07 20:59:18.353 8376-8376/io.geme.gemewidget I/com.marianhello.bgloc.LocationService: Service started
09-07 20:59:18.362 8376-8376/io.geme.gemewidget D/com.marianhello.bgloc.LocationService: Will start service with: Config[distanceFilter=10 stationaryRadius=20.0 desiredAccuracy=0 interval=30000 fastestInterval=5000 activitiesInterval=10000 isDebugging=false stopOnTerminate=true stopOnStillActivity=true startOnBoot=false startForeground=false notificationsEnabled=true locationProvider=0 nTitle=Geme nText=Watching out for Gemies nIconLarge= nIconSmall= nIconColor= url= syncUrl= syncThreshold=100 httpHeaders={} maxLocations=10000 postTemplate=null]
09-07 20:59:18.371 8376-8376/io.geme.gemewidget I/com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider: Creating DistanceFilterLocationProvider
09-07 20:59:18.380 8376-8376/io.geme.gemewidget E/AudioTrack: AudioFlinger could not create track, status: -12
09-07 20:59:18.381 8376-8376/io.geme.gemewidget E/ToneGenerator: AudioTrack(0x734d275000) set failed with error -12
    ToneGenerator init failed
```

Searching for 

> AudioFlinger could not create track, status: -12

there was no clear answer but it could look like the maximum number of audio streams had been reach, so it could be the switching between foreground and background dit not clean up properly

**Comment by tlacroix** [comment] 2018-12-08 22:45
Same here. Seems like the try/catch added to 2.0 was removed from 3.0 for some reason. I was able to fix it on my end by adding it again. I'll send a PR this week.
