### ISSUE TITLE
android version is not work in background

### ISSUE THREAD

**Issue by zuomoumou666** [mauron85/cordova-plugin-background-geolocation#92] opened 2016-06-14 16:45 UTC
1、why the app signals short tt beep representing recording coordinates and then long tt beep as to sending them to the server only when I open it the first time? 

2、I can only hear the long beep when I run it in background ,it shows that it sends no data to server at all.I wonder if sending data when moving ?

backgroundGeolocation.configure(callbackFn, failureFn, {
      desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 20,
      stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates 
      desiredAccuracy: 10,
      notificationIconColor: '#4CAF50',
      notificationTitle: 'Background tracking',
      notificationText: 'ENABLED',
      notificationIconLarge: 'icon_large', //filename without extension 
      notificationIconSmall: 'icon_small', //filename without extension 
      debug: true, // <-- enable this hear sounds for background-geolocation life-cycle. 
      locationProvider: backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
      interval: 30000, // <!-- poll for position every minute 
      fastestInterval: 30000,
      url: 'http://192.168.0.100:3000/path',
      httpHeaders: {
          "X-FOO": "bar"
      }
    });

**Comment by mauron85** [comment] 2016-06-14 22:00
Seems as duplicate of #88

**Comment by zuomoumou666** [comment] 2016-06-15 02:13
After exit stationary region, the plugin is not work?

**Comment by mauron85** [comment] 2016-06-17 10:19
1. no it should work fine
2. only when using the ANDROID_ACTIVITY_PROVIDER

**Comment by mauron85** [comment] 2017-11-21 06:53
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Closed** 2017-11-21 07:49 UTC
Labels: duplicate
